import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col fixed h-screen overflow-y-auto w-screen bg-stone-50 dark:bg-stone-900">
          <nav className="flex justify-between items-center p-4 bg-white fixed w-screen">
            <span className="text-2xl font-semibold text-stone-800 dark:text-stone-200">
              <Link href={{pathname: "/"}}>Monitor</Link>
            </span>
            <div className="flex flex-row gap-10">
              <Link href={{pathname: "/login"}} className="bg-stone-500 text-white py-1 px-4 rounded">Log In</Link>
            </div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  )
}
