import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { cookies } from 'next/headers'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { redirect } from 'next/navigation';
import { revalidatePath } from 'next/cache'
import LoginLogoutButton from './components/login-logout-button'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

  const cookieStore = cookies();
  const supabase = createServerComponentClient({ cookies: () => cookieStore });
  const {data: { session }} = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex flex-col fixed h-screen overflow-y-auto w-screen bg-white">
          <nav className="flex justify-between items-center p-4 bg-white fixed w-screen">
            <span className="text-2xl font-semibold text-sky-200">
              <Link href={{pathname: "/"}}>Pulseflow</Link>
            </span>
            <div className="flex flex-row gap-10">
              <LoginLogoutButton login={session == null}/>
            </div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  )
}
